# Generated by Django 5.2.6 on 2025-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brrowrecord',
            old_name='memeber',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(unique=True),
        ),
    ]
